//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace AsanSimulatorGUI.FCU_ORM
{

    [MemberDesignTimeVisibility(true)]
    public partial class FCUTest : XPObject
    {
        ushort ftest_index;
        public ushort test_index
        {
            get { return ftest_index; }
            set { SetPropertyValue<ushort>(nameof(test_index), ref ftest_index, value); }
        }
        bool ftest_status;
        public bool test_status
        {
            get { return ftest_status; }
            set { SetPropertyValue<bool>(nameof(test_status), ref ftest_status, value); }
        }
        string flarge_categ;
        public string large_categ
        {
            get { return flarge_categ; }
            set { SetPropertyValue<string>(nameof(large_categ), ref flarge_categ, value); }
        }
        string fsmall_categ;
        public string small_categ
        {
            get { return fsmall_categ; }
            set { SetPropertyValue<string>(nameof(small_categ), ref fsmall_categ, value); }
        }
        string ftest_name1;
        public string test_name1
        {
            get { return ftest_name1; }
            set { SetPropertyValue<string>(nameof(test_name1), ref ftest_name1, value); }
        }
        string ftest_name2;
        public string test_name2
        {
            get { return ftest_name2; }
            set { SetPropertyValue<string>(nameof(test_name2), ref ftest_name2, value); }
        }
        string ftest_name3;
        public string test_name3
        {
            get { return ftest_name3; }
            set { SetPropertyValue<string>(nameof(test_name3), ref ftest_name3, value); }
        }
        string ftest_name4;
        public string test_name4
        {
            get { return ftest_name4; }
            set { SetPropertyValue<string>(nameof(test_name4), ref ftest_name4, value); }
        }
        string ftest_result1;
        public string test_result1
        {
            get { return ftest_result1; }
            set { SetPropertyValue<string>(nameof(test_result1), ref ftest_result1, value); }
        }
        string ftest_result2;
        public string test_result2
        {
            get { return ftest_result2; }
            set { SetPropertyValue<string>(nameof(test_result2), ref ftest_result2, value); }
        }
        string ftest_result3;
        public string test_result3
        {
            get { return ftest_result3; }
            set { SetPropertyValue<string>(nameof(test_result3), ref ftest_result3, value); }
        }
        string ftest_result4;
        public string test_result4
        {
            get { return ftest_result4; }
            set { SetPropertyValue<string>(nameof(test_result4), ref ftest_result4, value); }
        }
        ushort fvoltage_set;
        public ushort voltage_set
        {
            get { return fvoltage_set; }
            set { SetPropertyValue<ushort>(nameof(voltage_set), ref fvoltage_set, value); }
        }
        ushort fresistor_set;
        public ushort resistor_set
        {
            get { return fresistor_set; }
            set { SetPropertyValue<ushort>(nameof(resistor_set), ref fresistor_set, value); }
        }
        bool fneed_graph;
        public bool need_graph
        {
            get { return fneed_graph; }
            set { SetPropertyValue<bool>(nameof(need_graph), ref fneed_graph, value); }
        }
        [Association(@"SMALL_TESTReferencesFCU_test_list"), Aggregated]
        public XPCollection<SMALL_TEST> SMALL_TESTs { get { return GetCollection<SMALL_TEST>(nameof(SMALL_TESTs)); } }
    }

}
