//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace AsanSimulatorGUI.FCU_ORM
{

    [MemberDesignTimeVisibility(true)]
    public partial class SMALL_TEST : XPObject
    {
        FCUTest fFCU_test_list;
        [Association(@"SMALL_TESTReferencesFCU_test_list")]
        public FCUTest FCU_test_list
        {
            get { return fFCU_test_list; }
            set { SetPropertyValue<FCUTest>(nameof(FCU_test_list), ref fFCU_test_list, value); }
        }
        string fsmall_tag;
        public string small_tag
        {
            get { return fsmall_tag; }
            set { SetPropertyValue<string>(nameof(small_tag), ref fsmall_tag, value); }
        }
        ushort fref_L;
        public ushort ref_L
        {
            get { return fref_L; }
            set { SetPropertyValue<ushort>(nameof(ref_L), ref fref_L, value); }
        }
        ushort fref_R;
        public ushort ref_R
        {
            get { return fref_R; }
            set { SetPropertyValue<ushort>(nameof(ref_R), ref fref_R, value); }
        }
        ushort fmeasure_value;
        public ushort measure_value
        {
            get { return fmeasure_value; }
            set { SetPropertyValue<ushort>(nameof(measure_value), ref fmeasure_value, value); }
        }
        ushort fvalue_min;
        public ushort value_min
        {
            get { return fvalue_min; }
            set { SetPropertyValue<ushort>(nameof(value_min), ref fvalue_min, value); }
        }
        ushort fvalue_max;
        public ushort value_max
        {
            get { return fvalue_max; }
            set { SetPropertyValue<ushort>(nameof(value_max), ref fvalue_max, value); }
        }
    }

}
